export const ALL_ITEMS = [
  { id: 'apple', emoji: '🍎', label: 'りんご' },
  { id: 'key', emoji: '🔑', label: '鍵' },
  { id: 'hat', emoji: '🎩', label: '帽子' },
  { id: 'umbrella', emoji: '☂️', label: '傘' },
  { id: 'clock', emoji: '⏰', label: '時計' },
  { id: 'glasses', emoji: '👓', label: '眼鏡' },
  { id: 'bag', emoji: '👜', label: 'かばん' },
  { id: 'shoe', emoji: '👞', label: '靴' },
  { id: 'book', emoji: '📕', label: '本' },
  { id: 'flower', emoji: '🌷', label: '花' },
  { id: 'cup', emoji: '☕', label: 'カップ' },
  { id: 'candle', emoji: '🕯️', label: 'ろうそく' },
  { id: 'letter', emoji: '✉️', label: '手紙' },
  { id: 'coin', emoji: '🪙', label: '硬貨' },
  { id: 'camera', emoji: '📷', label: 'カメラ' },
  { id: 'lamp', emoji: '💡', label: 'ランプ' },
  { id: 'scissors', emoji: '✂️', label: 'はさみ' },
  { id: 'ring', emoji: '💍', label: '指輪' },
  { id: 'phone', emoji: '📱', label: '電話' },
  { id: 'boat', emoji: '⛵', label: '船' },
];
